In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Original array:", arr)
print("Adding 2:", arr + 2)
print("Multiplying by 3:", arr * 3)
print("Dividing by 2:", arr / 2)

Original array: [1 2 3 4 5]
Adding 2: [3 4 5 6 7]
Multiplying by 3: [ 3  6  9 12 15]
Dividing by 2: [0.5 1.  1.5 2.  2.5]


In [2]:
arr = np.array([1, 2, 3, 6, 4, 5])

print("Original Array:", arr)
print("Reversed Array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

unique_x, counts_x = np.unique(x, return_counts=True)
max_count_x = np.max(counts_x)
frequent_x = unique_x[counts_x == max_count_x]

print("Most frequent value in x:", frequent_x)
print("Indices in x:", np.where(np.isin(x, frequent_x))[0])

unique_y, counts_y = np.unique(y, return_counts=True)
max_count_y = np.max(counts_y)
frequent_y = unique_y[counts_y == max_count_y]

print("Most frequent value in y:", frequent_y)
print("Indices in y:", np.where(np.isin(y, frequent_y))[0])

Original Array: [1 2 3 6 4 5]
Reversed Array: [5 4 6 3 2 1]
Most frequent value in x: [1]
Indices in x: [0 5 7 8 9]
Most frequent value in y: [1 3]
Indices in y: [0 1 2 4 8 9]


In [3]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])

1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
ucs420_your_name = np.linspace(10, 100, 25)

print("Array:", ucs420_your_name)
print("Dimensions:", ucs420_your_name.ndim)
print("Shape:", ucs420_your_name.shape)
print("Total elements:", ucs420_your_name.size)
print("Data type:", ucs420_your_name.dtype)
print("Total bytes:", ucs420_your_name.nbytes)

transposed_ucs420_your_name = ucs420_your_name.reshape(25, 1)
print("Transpose using reshape():")
print(transposed_ucs420_your_name)

transposed_using_T = ucs420_your_name.T
print("Transpose using T:")
print(transposed_using_T)

print("Yes, T can be used, but for a 1-D array T does not change its shape.")
print("To get a column vector, reshape(25, 1) is required.")

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Yes, T can be used, but for a 1-D array T does not change its shape.
To get a column vector, reshape(25, 1) is required.


In [5]:
ucs420_your_name = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

print("Original Array:")
print(ucs420_your_name)

print("Mean:", np.mean(ucs420_your_name))
print("Median:", np.median(ucs420_your_name))
print("Maximum:", np.max(ucs420_your_name))
print("Minimum:", np.min(ucs420_your_name))
print("Unique elements:", np.unique(ucs420_your_name))

reshaped_ucs420_your_name = ucs420_your_name.reshape(4, 3)

print("Reshaped Array (4 x 3):")
print(reshaped_ucs420_your_name)

resized_ucs420_your_name = np.resize(reshaped_ucs420_your_name, (2, 3))

print("Resized Array (2 x 3):")
print(resized_ucs420_your_name)

Original Array:
[[10 20 30 40]
 [50 60 70 80]
 [90 15 20 35]]
Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped Array (4 x 3):
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized Array (2 x 3):
[[10 20 30]
 [40 50 60]]
