In [1]:
import numpy as np

In [2]:
temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])

temperature_error = temperature + 2
print("Temperatures after adding 2°C:", temperature_error)

fahrenheit = (9 / 5) * temperature + 32
print("Temperatures in Fahrenheit:", fahrenheit)

readings_greater_32 = temperature[temperature > 32]
print("Readings greater than 32°C:", readings_greater_32)

count = np.sum(temperature > 32)
print("Number of readings greater than 32°C:", count)

print("Vectorization performs operations on the entire array at once,")
print("while Boolean indexing selects required values without explicit loops.")


Temperatures after adding 2°C: [27 30 33 37 40 29 35 42]
Temperatures in Fahrenheit: [ 77.   82.4  87.8  95.  100.4  80.6  91.4 104. ]
Readings greater than 32°C: [35 38 33 40]
Number of readings greater than 32°C: 4
Vectorization performs operations on the entire array at once,
while Boolean indexing selects required values without explicit loops.


In [3]:
steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

print("Total steps:", np.sum(steps))
print("Mean steps:", np.mean(steps))
print("Maximum steps:", np.max(steps))
print("Minimum steps:", np.min(steps))

print("Total steps for each day:", np.sum(steps, axis=0))
print("Total steps for each user:", np.sum(steps, axis=1))

max_position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum steps:", max_position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum steps: (np.int64(3), np.int64(2))


In [4]:
original = np.array([1, 2, 3, 4, 5, 6])

subset = original[1:5]
subset[0] = 999

print("Original after modifying subset:", original)
print("Subset:", subset)

copied_array = original[1:5].copy()
copied_array[0] = 500

print("Original after modifying copied array:", original)
print("Copied array:", copied_array)

matrix = np.arange(1, 13).reshape(3, 4)

print("3 x 4 Matrix:")
print(matrix)

print("First row:", matrix[0])
print("Last row:", matrix[-1])
print("Second column:", matrix[:, 1])
print("Rows 1-2 and columns 2-3:", matrix[0:2, 1:3])

flattened = matrix.flatten()
raveled = matrix.ravel()

print("Flattened array:", flattened)
print("Raveled array:", raveled)

raveled[0] = 100
print("Matrix after modifying ravel:", matrix)
print("Raveled array:", raveled)

flattened[1] = 200
print("Matrix after modifying flatten:", matrix)
print("Flattened array:", flattened)

print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original after modifying subset: [  1 999   3   4   5   6]
Subset: [999   3   4   5]
Original after modifying copied array: [  1 999   3   4   5   6]
Copied array: [500   3   4   5]
3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3: [[2 3]
 [6 7]]
Flattened array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Raveled array: [ 1  2  3  4  5  6  7  8  9 10 11 12]
Matrix after modifying ravel: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Raveled array: [100   2   3   4   5   6   7   8   9  10  11  12]
Matrix after modifying flatten: [[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]
Flattened array: [  1 200   3   4   5   6   7   8   9  10  11  12]
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [5]:
X = np.array([
    [6, 70, 3],
    [5, 50, 6],
    [8, 80, 2],
    [4, 30, 8]
])

y = np.array([40, 65, 30, 85])

print("Shape of X:", X.shape)
print("Dimensions of X:", X.ndim)

print("X Transpose:")
print(X.T)

print("X.T represents features as rows and users as columns.")

XtX = X.T @ X
print("X.T @ X:")
print(XtX)

inverse = np.linalg.inv(XtX)
print("Inverse of X.T @ X:")
print(inverse)

beta = inverse @ X.T @ y
print("OLS coefficients:", beta)

print("The coefficients represent the effect of sleep hours,")
print("activity level, and stress level on the assistance score.")

new_user = np.array([5, 40, 7])
predicted_score = new_user @ beta

print("Predicted assistance score:", predicted_score)

Shape of X: (4, 3)
Dimensions of X: 2
X Transpose:
[[ 6  5  8  4]
 [70 50 80 30]
 [ 3  6  2  8]]
X.T represents features as rows and users as columns.
X.T @ X:
[[  141  1430    96]
 [ 1430 14700   910]
 [   96   910   113]]
Inverse of X.T @ X:
[[ 1.10521428 -0.09848746 -0.14581398]
 [-0.09848746  0.00891203  0.01190129]
 [-0.14581398  0.01190129  0.0368847 ]]
OLS coefficients: [-0.15921454  0.14083853 10.06302242]
The coefficients represent the effect of sleep hours,
activity level, and stress level on the assistance score.
Predicted assistance score: 75.27862544779117
